apiVersion: v1
kind: Service
metadata:
  name: streamflix-backend-service
  namespace: streamflix
  labels:
    app: streamflix-backend
    tier: backend
spec:
  selector:
    app: streamflix-backend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP